package in.wynk.payment.dto.payu;

public interface PayUConstants {
    String PAYU_PG = "pg";
    String PAYU_SI_KEY = "si";
    String PAYU_HASH = "hash";
    String PAYU_VARIABLE1 = "var1";
    String PAYU_VARIABLE = "var";
    String PAYU_BSYS_PARAM = "bsys";
    String PAYU_REQUEST_TYPE = "rt";
    String PAYU_COMMAND = "command";
    String PAYU_SUCCESS_URL = "surl";
    String PAYU_FAILURE_URL = "furl";
    String PAYU_MERCHANT_KEY = "key";
    String PAYU_CHARGING_INFO = "info";
    String PAYU_UDF1_PARAMETER = "udf1";
    String PAYU_CARD_NUMBER = "card_no";
    String PAYU_CUSTOMER_EMAIL = "email";
    String PAYU_REQUEST_ID = "requestId";
    String PAYU_CARD_TOKEN = "card_token";
    String PAYU_CUSTOMER_MSISDN = "phone";
    String PAYU_FREE_TRIAL = "free_trial";
    String PAYU_SI_DETAILS = "si_details";
    String PAYU_API_VERSION = "api_version";
    String PAYU_STATUS_CAPTURED = "captured";
    String PAYU_SI_STATUS_FAILURE = "failed";
    String PAYU_PRODUCT_INFO = "productinfo";
    String PAYU_CARD_DETAILS = "CardDetails";
    String PAYU_TRANSACTION_AMOUNT = "amount";
    String PAYU_NETBANKING_MODE = "netbanking";
    String PAYU_STATUS_NOT_FOUND = "Not Found";
    String PAYU_PAYMENT_SOURCE_SIST = "sist";
    String PAYU_CUSTOMER_FIRSTNAME = "firstname";
    String PAYU_REQUEST_TRANSACTION_ID = "txnid";
    String PAYU_RESPONSE_AUTH_PAYUID = "authPayuId";
    String PAYU_ENFORCE_PAYMENT = "enforce_payment";
    String PAYU_USER_CREDENTIALS = "user_credentials";
    String PAYU_ENFORCE_PAY_METHOD = "enforce_paymethod";
    String PAYU_RESPONSE_AUTH_PAYUID_SMALL = "authpayuid";
    String PAYU_REDIRECT_MESSAGE = "Redirecting to PayU ";
    String PAYU_IS_FALLBACK_ATTEMPT = "isFallbackAttempt";
    String PAYU_REFUND_TRANSACTION_TYPE = "REFUND_TYPE";
    String PAYU_CHARGING_TRANSACTION_TYPE = "CHARGE_TYPE";
}
