cors:
  allowed:
    origins:
      - 'https://wcf-utils.wynk.in'
      - 'https://brand.wynk.in'
    methods: GET, PUT, PATCH, POST, OPTIONS, DELETE
  maxAge: 3600
wynk:
  mongodb:
    enabled: true
    sources:
      client:
        nodes: 10.40.12.162,10.40.12.216,10.40.12.45
        username: user_client_details
        password: BBcUV5rsWf
        database: client_details
      se:
        nodes: 10.40.12.162:27017,10.40.12.216:27017,10.40.12.45:27017
        username: user_sedb
        password: YaNcVsxQ8J
        database: sedb
      testingConfig:
        nodes: 10.40.12.162,10.40.12.216,10.40.12.45
        username: user_testing_config
        password: fEP7H3m4pF
        database: testingConfig
      ads:
        nodes: 10.40.12.162,10.40.12.216,10.40.12.45
        username: user_ads_db
        password: jUx2vYHsud
        database: ads_db
      payment:
        nodes: 10.40.12.162,10.40.12.216,10.40.12.45
        username: user_payments
        password: tHdPNyp6Du
        database: payments
      coupons:
        nodes: 10.40.12.162,10.40.12.216,10.40.12.45
        username: user_coupons
        password: 6sSUZcp2gy
        database: coupons
        ########### Mongo Pool Config ###########
    minConnectionsPerHost: 10
    maxConnectionsPerHost: 20
    threadsAllowedToBlockForConnectionMultiplier: 5
    serverSelectionTimeoutMs: 10000
    maxWaitTime: 10000
    connectTimeout: 2000
    socketTimeout: 5000
    readPreference: primary

amazon:
  sdk:
    regions: ap-south-1

resilience:
  retryProperties:
    maxAttempts: 3
    waitDuration: 10000

spring:
  datasource:
    url: jdbc:mysql://wcf-payments-production.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
    username: huygens
    password: 2dtRAHGI5OhfBj1hNkpd
    hikari:
      jdbc-url: jdbc:mysql://wcf-payments-production.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
      username: huygens
      password: 2dtRAHGI5OhfBj1hNkpd
      driver-class-name: com.mysql.cj.jdbc.Driver
      registerMbeans: true
      auto-commit: false
      connectionTimeout: 2000
      idleTimeout: 10000
      maxLifetime: 30000
      poolName: payment-datasource-pool-dev
      minimum-idle: 50
      maximumPoolSize: 200

  #### JPA props ######
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.format_sql: false
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: validate
      hibernate.jdbc.time_zone: Asia/Kolkata

service:
  subscription:
    api:
      root: http://subscription.wcf.internal

wcf:
  s3:
    bucket: wcf-brand
  brandChannel:
    hostname: https://brand.wynk.in
