app:
  cors:
    allowed:
      origins:
        - 'http://localhost:4200'

wynk:
  mongodb:
    enabled: true
    sources:
      ads:
        nodes: 10.80.0.128:27017,10.80.0.240:27017
        username: user_ads_db
        password: 7khkPtsGkw
        database: ads_db
      se:
        nodes: 10.80.0.128:27017,10.80.0.240:27017
        username: user_sedb
        password: z8wcCM5qjw
        database: sedb
      payment:
        nodes: 10.80.0.128,10.80.0.240
        username: user_payments
        password: zS7VvjYRSE
        database: payments
      testingConfig:
        nodes: 10.80.0.128,10.80.0.240
        username: user_testing_config
        password: UcFtLLxX2t
        database: testingConfig
      client:
        nodes: 10.80.0.128,10.80.0.240
        username: user_client_details
        password: BBcUV5rsWf
        database: client_details

spring:
  ##### mysql database props #####
  datasource:
    url: jdbc:mysql://wcf-payments-staging.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
    username: admin
    password: o7QZ?!n=eu
    hikari:
      jdbc-url: jdbc:mysql://wcf-payments-staging.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
      username: admin
      password: o7QZ?!n=eu
      driver-class-name: com.mysql.cj.jdbc.Driver
      registerMbeans: true
      auto-commit: false
      connectionTimeout: 5000
      idleTimeout: 10000
      maxLifetime: 30000
      poolName: payment-datasource-pool-dev
      minimum-idle: 10
      maximumPoolSize: 100

####### Http Client Props #######
http:
  enableTemplateRegistration: true
  templates:
    subscriptionHttpTemplate:
      pool:
        connection:
          max: 250
          maxPerHost: 200
          validateAfterInActivity: 100
          timeout: 4000
          defaultKeepAliveTime: 500
          closeIdleWaitTime: 500
          socket:
            timeout: 6000
            factory:
              type: both
          request:
            timeout: 1000

service:
  subscription:
    api:
      root: http://subscription-staging.wcf.internal

logging:
  path: /tmp

amazon:
  sdk:
    regions: ap-south-1

resilience:
  retryProperties:
    maxAttempts: 3
    waitDuration: 10000

wcf:
  s3:
    bucket: wcf-db-backups
  brandChannel:
    hostname: https://brand.wynk.in
cors:
  allowed:
    origins:
      - '*'
    methods: GET, PUT, PATCH, POST, OPTIONS
  maxAge: 3600
