app:
  cors:
    allowed:
      origins:
        - http://localhost:3000

  mongo:
    sources:
      ads:
        nodes: 10.80.0.128:27017,10.80.0.240:27017
        username: user_ads_db
        password: 7khkPtsGkw
        database: ads_db
      se:
        nodes: 10.80.0.128:27017,10.80.0.240:27017
        username: user_sedb
        password: z8wcCM5qjw
        database: sedb

wynk:
  mongodb:
    enabled: true
    sources:
      client:
        nodes: 10.80.0.128,10.80.0.240
        username: user_client_details
        password: BBcUV5rsWf
        database: client_details

amazon:
  sdk:
    regions: ap-south-1

resilience:
  retryProperties:
    maxAttempts: 3
    waitDuration: 10000

spring:
  datasource:
    url: jdbc:mysql://wcf-payments-staging.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
    username: admin
    password: o7QZ?!n=eu
    hikari:
      jdbc-url: jdbc:mysql://wcf-payments-staging.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
      username: admin
      password: o7QZ?!n=eu
      driver-class-name: com.mysql.cj.jdbc.Driver
      registerMbeans: true
      auto-commit: false
      connectionTimeout: 5000
      idleTimeout: 10000
      maxLifetime: 30000
      poolName: payment-datasource-pool-dev
      minimum-idle: 10
      maximumPoolSize: 100

  #### JPA props ######
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.format_sql: false
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: validate
      hibernate.jdbc.time_zone: Asia/Kolkata

wcf:
  s3:
    bucket: wcf-brand
  brandChannel:
    hostname: https://brand.wynk.in

cors:
  allowed:
    origins:
      - 'https://wcf-utils-dev.wynk.in'
    methods: GET, PUT, PATCH, POST, OPTIONS
  maxAge: 3600