cassandra:
      contactpoints: 127.0.0.1
      port: 9042
      keyspace: user_targeting
      jmxEnabled: false

cloud:
   aws:
     stack:
       auto: false
     credentials:
        instanceProfile: true
     region:
        static: ap-south-1
app:
  batch:
    utJob:
      consistencyLevel: ONE # Check ConsistencyLevel.java for possible values
      chunks: 100
      defaultTTL: 5
      launcher:
        concurrencyLimit: 20

logging:
  path: /tmp
