package in.wynk.utils.constant;

import java.util.Arrays;
import java.util.List;

@Deprecated
public enum ProvisionType {
    DATA, SUBSCRIPTION, NO_PROVISION, DISCOUNT_PROVISION, COMMUNICATION, BROADBAND_DATA, POSTPAID_DATA, POSTPAID_DATA_PLUS_VAS, POSTPAID_4G_CPE, DEFAULT_SUBSCRIPTION, MANUAL_PROVISION;

    public static List<ProvisionType> SUBSCRIPTION_PROVISION = Arrays.asList(SUBSCRIPTION, DEFAULT_SUBSCRIPTION, MANUAL_PROVISION, POSTPAID_DATA, POSTPAID_DATA_PLUS_VAS);

}