### Rest Template props ###
http:
  enableTemplateRegistration: true
  templates:
    subscriptionHttpTemplate:
      pool:
        connection:
          max: 50
          maxPerHost: 5
          validateAfterInActivity: 100
          timeout: 4000
          defaultKeepAliveTime: 500
          closeIdleWaitTime: 500
          socket:
            timeout: 6000
            factory:
              type: both
          request:
            timeout: 1000