package in.wynk.coupon.core.constant;

public enum CouponEligibilityCode {

    INELIGIBLE_PAYMENT_METHOD,
    INELIGIBLE_ACTIVE_PLAN_ID,
    INELIGIBLE_THANKS_SEGMENT,
    INELIGIBLE_COHORT_SEGMENT,
    INELIGIBLE_WHITELISTED_USER,
    INELIGIBLE_PURCHASING_PLAN_ID,
    INELIGIBLE_PURCHASING_ITEM_ID,
    COUPON_LIMIT_EXCEED,
    COUPON_EXPIRED,
    ELIGIBILITY_FAILURE

}
