### Rest Template props ###
http:
  enableTemplateRegistration: true
  templates:
    subscriptionHttpTemplate:
      pool:
        connection:
          max: 20
          maxPerHost: 5
          validateAfterInActivity: 100
          timeout: 4000
          defaultKeepAliveTime: 500
          closeIdleWaitTime: 500
          socket:
            timeout: 6000
            factory:
              type: both
          request:
            timeout: 1000
    partnerNotifierTemplate:
      pool:
        connection:
          max: 20
          maxPerHost: 5
          validateAfterInActivity: 100
          timeout: 4000
          defaultKeepAliveTime: 500
          closeIdleWaitTime: 500
          socket:
            timeout: 6000
            factory:
              type: both
          request:
            timeout: 1000

###### Order Queue props #####
order:
  pooling:
    queue:
      placement:
        enabled: true
        name: wcf-staging-order-placement.fifo
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 5
          consumer:
            delay: 5
            delayTimeUnit: SECONDS
          producer:
            delayInSecond: 5
      fulfilment:
        enabled: true
        name: wcf-staging-order-fulfilment
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 5
          consumer:
            delay: 5
            delayTimeUnit: SECONDS
          producer:
            delayInSecond: 5
      notification:
        enabled: false
        name: wcf-staging-order-notification
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 5
          consumer:
            delay: 5
            delayTimeUnit: SECONDS
            timeout: 1000
          producer:
            delayInSecond: 5
      deferred:
        enabled: true
        name: wcf-staging-deferred-orders-scheduler
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          consumer:
            delay: 20
            delayTimeUnit: SECONDS
          producer:
            delayInSecond: 180

subscription:
  pooling:
    queue:
      provision:
        enabled: true
        name: wcf-staging-subscription
        sqs:
          producer:
            delayInSecond: 1

#Deferred scheduler order props
deferred:
  orders:
    offset:
      day: 1

#### Hystrix Props #####
hystrix:
  enabled: true
  order:
    commandGroupKey: manageOrder
    placement:
      commandKey: place
      timeout: 2100
      errorPercentage: 10
    fulfilment:
      commandKey: fulfil
      timeout: 2100
      errorPercentage: 10

###### Cache Props #######
cache:
  enabled: true
  mode: composite
  ####### Redis Props #######
  redis:
    name: l2cache-local
    mode: standalone
    standalone:
      host: 10.80.0.22
      port: 6379
    cache:
      ttl: 2
      timeunit: minutes
      usePrefix: false
      cacheNullValues: false
      keyPrefix: LOCAL
    usePooling: true
    enableJmx: false
    jmxPrefix: local
    connection:
      timeout: 1000
      maxTotal: 200
      minIdle: 50
      maxIdle: 100
  ####### Caffeine Props ######
  caffeine:
    metrics: true
    nullable: false
    eviction:
      size:
        initial: 10
        maximum: 500
      time:
        fixed: true
        expireAfterWrite: 1
        expireAfterAccess: 1
        timeunit: minutes
      #cache.caffeine.eviction.reference.weakKeys=false
      #cache.caffeine.eviction.reference.weakValues=false
      #cache.caffeine.eviction.reference.softValues=false


